import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection, importProvidersFrom } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { camelCaseInterceptor } from './core/interceptors/camel-case.interceptor';
import {
  LucideAngularModule,
  Eye,
  EyeOff,
  Mail,
  KeyRound,
  ArrowLeft,
  ChevronDown,
  Check,
  Zap,
  ShieldCheck,
  Gift,
  Gauge,
  Bot,
  Headset,
  MailCheck,
  Pencil,
  Info,
  Rocket,
  Building2,
  X,
  Loader2,
  LayoutDashboard,
  Users,
  FileText,
  MessageSquare,
  Send,
  BarChart2,
  Settings,
  HelpCircle,
  MessageCircle,
  TrendingUp,
  TrendingDown,
  DollarSign,
  TriangleAlert,
  CircleCheck,
  Target,
  ChevronRight,
  Plus,
  Search,
  Filter,
  RefreshCw,
  Trash2,
  Edit2,
  Clock,
  User,
  Phone,
  Star,
  ExternalLink
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()),
    provideClientHydration(withEventReplay()),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor, camelCaseInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        Eye,
        EyeOff,
        Mail,
        KeyRound,
        ArrowLeft,
        ChevronDown,
        Check,
        Zap,
        ShieldCheck,
        Gift,
        Gauge,
        Bot,
        Headset,
        MailCheck,
        Pencil,
        Info,
        Rocket,
        Building2,
        X,
        Loader2,
        LayoutDashboard,
        Users,
        FileText,
        MessageSquare,
        Send,
        BarChart2,
        Settings,
        HelpCircle,
        MessageCircle,
        TrendingUp,
        TrendingDown,
        DollarSign,
        TriangleAlert,
        CircleCheck,
        Target,
        ChevronRight,
        Plus,
        Search,
        Filter,
        RefreshCw,
        Trash2,
        Edit2,
        Clock,
        User,
        Phone,
        Star,
        ExternalLink
      })
    )
  ]
};
