"""add communications module

Revision ID: 202df094637c
Revises: e808a258ace1
Create Date: 2026-02-09 01:28:03.847314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202df094637c'
down_revision: Union[str, Sequence[str], None] = 'e808a258ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='workflow_status'), nullable=False),
    sa.Column('trigger_description', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_executions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', postgresql.ENUM('WHATSAPP', 'EMAIL', 'SMS', 'CALL', 'AI_VOICE', name='channel_type', create_type=False), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='template_status'), nullable=False),
    sa.Column('language', sa.String(length=5), server_default='es', nullable=False),
    sa.Column('times_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('click_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reply_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', postgresql.ENUM('WHATSAPP', 'EMAIL', 'SMS', 'CALL', 'AI_VOICE', name='channel_type', create_type=False), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('delay_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delay_hours', sa.Integer(), server_default='0', nullable=False),
    sa.Column('send_time', sa.String(length=5), nullable=True),
    sa.Column('condition_type', sa.Enum('NONE', 'PREVIOUS_NOT_OPENED', 'PREVIOUS_NOT_REPLIED', 'PREVIOUS_BOUNCED', 'INVOICE_STILL_UNPAID', name='step_condition_type'), nullable=False),
    sa.Column('fallback_channel', sa.String(length=20), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_instructions', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['collection_workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'step_order', name='uq_workflow_step_order')
    )
    op.create_table('communication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('debtor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('workflow_step_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('sent_by_user_id', sa.UUID(), nullable=True),
    sa.Column('channel', postgresql.ENUM('WHATSAPP', 'EMAIL', 'SMS', 'CALL', 'AI_VOICE', name='channel_type', create_type=False), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='communication_direction'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'QUEUED', 'SENDING', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'REPLIED', 'FAILED', 'BOUNCED', 'CANCELLED', name='communication_status'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('recipient_address', sa.String(length=255), nullable=True),
    sa.Column('external_message_id', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['collection_workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comm_logs_org_campaign', 'communication_logs', ['organization_id', 'campaign_id'], unique=False)
    op.create_index('ix_comm_logs_org_channel_status', 'communication_logs', ['organization_id', 'channel', 'status'], unique=False)
    op.create_index('ix_comm_logs_org_created', 'communication_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_comm_logs_org_debtor', 'communication_logs', ['organization_id', 'debtor_id'], unique=False)
    op.create_table('communication_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('communication_log_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('SCHEDULED', 'QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'FAILED', 'UNSUBSCRIBED', 'COMPLAINED', 'PAYMENT_PROMISE', 'PAYMENT_MADE', 'ESCALATED', 'CANCELLED', name='communication_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['communication_log_id'], ['communication_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaigns', sa.Column('workflow_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'collection_workflows', ['workflow_id'], ['id'])
    # Clear any existing string template_id values before type change
    op.execute("UPDATE stage_actions SET template_id = NULL WHERE template_id IS NOT NULL")
    op.alter_column('stage_actions', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               comment=None,
               existing_comment='Reference to message template',
               existing_nullable=True,
               postgresql_using="template_id::uuid")
    op.create_foreign_key(None, 'stage_actions', 'message_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage_actions', type_='foreignkey')
    op.alter_column('stage_actions', 'template_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               comment='Reference to message template',
               existing_nullable=True)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'workflow_id')
    op.drop_table('communication_events')
    op.drop_index('ix_comm_logs_org_debtor', table_name='communication_logs')
    op.drop_index('ix_comm_logs_org_created', table_name='communication_logs')
    op.drop_index('ix_comm_logs_org_channel_status', table_name='communication_logs')
    op.drop_index('ix_comm_logs_org_campaign', table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_table('workflow_steps')
    op.drop_table('message_templates')
    op.drop_table('collection_workflows')
    # ### end Alembic commands ###
