"""add debtors invoices and payments tables

Revision ID: 60c41a4235a3
Revises: eec7d321498a
Create Date: 2026-02-02 23:37:57.184683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60c41a4235a3'
down_revision: Union[str, Sequence[str], None] = 'eec7d321498a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('erp_id', sa.String(length=100), nullable=True, comment='External ID from ERP (SAP/QBO)'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='CUIT/RFC of the client'),
    sa.Column('risk_score', sa.Integer(), nullable=True, comment='Risk score 0-100'),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True, comment='Tags for segmentation (e.g., VIP, Retail)'),
    sa.Column('ai_profile_summary', sa.Text(), nullable=True, comment='AI-generated summary of debtor behavior'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('debtor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Original amount'),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='Pending amount (updated with payments)'),
    sa.Column('currency', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', 'DISPUTED', name='invoice_status'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True, comment='Link to PDF if uploaded'),
    sa.Column('erp_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra data from ERP'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('debtor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True, comment='Transfer, Check, etc.'),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('proof_file_url', sa.Text(), nullable=True, comment='Uploaded receipt'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_allocations')
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('debtors')
    # ### end Alembic commands ###
    
    # Drop enum type
    op.execute('DROP TYPE IF EXISTS invoice_status')
