"""create campaigns tables

Revision ID: e808a258ace1
Revises: 60c41a4235a3
Create Date: 2026-02-08 21:17:42.182293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e808a258ace1'
down_revision: Union[str, Sequence[str], None] = '60c41a4235a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.Enum('PREVENTIVE', 'FRIENDLY', 'ASSERTIVE', 'LEGAL', name='campaign_type'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('strategy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Audience filters, scheduling, channel config, AI settings'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day_start', sa.Integer(), nullable=False),
    sa.Column('day_end', sa.Integer(), nullable=False),
    sa.Column('tone_instructions', sa.Text(), nullable=True, comment='AI tone instructions for this stage'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'EMAIL', 'SMS', 'CALL', 'AI_VOICE', name='channel_type'), nullable=False),
    sa.Column('trigger_day', sa.Integer(), nullable=False, comment='Day within the stage to trigger this action'),
    sa.Column('template_id', sa.String(length=100), nullable=True, comment='Reference to message template'),
    sa.Column('ai_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['campaign_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_actions')
    op.drop_table('campaign_stages')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
